#!/bin/bash

cd /root/puppet_openstack_builder/install-scripts
chmod 775 master.sh
chmod 775 setup.sh

/root/puppet_openstack_builder/install-scripts/setup.sh

/root/puppet_openstack_builder/install-scripts/master.sh

