#!/bin/bash

#install required apps
apt-get install -y git
apt-get install -d -y puppet rubygems curl python-yaml apache2


# Install openstack-installer
cd /root/
if ! [ -f openstack-installer ]; then
    git clone https://github.com/CiscoSystems/openstack-installer.git /root/openstack-installer
fi

