#!/bin/bash

#install required apps
apt-get install -y git
apt-get install -d -y puppet rubygems curl python-yaml apache2


# Install puppet_openstack_builder
cd /root/
if ! [ -f puppet_openstack_builder ]; then
    git clone https://github.com/CiscoSystems/puppet_openstack_builder.git /root/puppet_openstack_builder
fi

